# Menus
menu:
  Home: .
  About: about/biography
  Archives: archives

# Customize
customize:
    logo:
        enabled: true
        width: 40
        height: 40
        url: images/logo.png
    profile:
        enabled: true # Whether to show profile bar
        avatar: images/profile.png
        gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
        author: Daniel Alksnis
        firstname: Daniel
        lastname: Alksnis
        author_title: Engineer
        location: Toronto, Canada
    highlight: monokai
    sidebar: right # sidebar position, options: left, right
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: # path to favicon
    social_links:
        github: http://github.com/st3xupery
        twitter: https://twitter.com/danielalksnis
        linkedin: https://ca.linkedin.com/in/daniel-alksnis-2ba07250

# Widgets
widgets:
    - recent_posts
    - category
    - archive
    - tagcloud
    - links

# Search
search:
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    disqus: danielalksnis # enter disqus shortname here
    duoshuo: # enter duoshuo shortname here
    youyan: # enter youyan uid here

# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    google_analytics: # enter the tracking ID for your Google Analytics
    google_site_verification: hd_edzSNlKBqbEyb1QcxTp92_jq2eNI5GIlRN6NYrDc
    baidu_analytics: # enter Baidu Analytics hash key

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
        ClearMine: http://clearmine.io
        Hexo: http://hexo.io
